Created Thread pool
Kirill-ML19/spbu-python-course pull request #3
Opened 2024-10-24 20:46 UTC by Kirill-ML19

# Задача 4. Пул потоков

* **Дедлайн**: 24.10.2024, 23:59
* Полный балл: 10

## Задача

- [X] Реализовать паттерн "пул потоков".
  - [X] Число потоков задаётся константой в классе пула или параметром конструктора.
  - [X] У каждого потока есть два состояния: ожидание задачи, выполнение задачи.
  - [X] Задача --- некая функция проводящая вычисления и возвращающая результат.
  - [X] Добавление задачи осуществляется с помощью метода `enqueue(task)`
  - [X] При добавлении задачи, если в пуле есть ожидающий поток, то он должен приступить к её выполнению. Иначе задача будет ожидать исполнения, пока не освободится какой-нибудь поток.
  - [X] Метод `dispose` должен завершать работу потоков. Уже запущенные задачи не прерываются, но новые задачи не принимаются на исполнение потоками из пула.
  - [X] Ограничения:
    - Разрешено использовать только пакет threading
    - Для каждого базового сценария должен быть написан несложный тест
    - Также должен быть написан тест, проверяющий, что в пуле действительно не менее `n` потоков
  - [X] Допущения:
    - Использование класса для реализации пула потоков необязательно
- [ ] **(Доп., +2 балла)** С помощью `concurrent.futures` реализовать параллельное вычисление суммы полного декартового произведения множества целых чисел

2024-10-25 09:33 UTC, Krekep requested changes
Необходимы исправления.
Также не выполнены требования по названию PR

2024-10-25 09:33 UTC, Krekep commented on tests/test_thread_pool.py
Не хватает теста проверяющего, что в пуле действительно находится `n` рабочих потоков

2024-10-31 14:41 UTC, Kirill-ML19 commented on tests/test_thread_pool.py
Добавил тест

2024-11-02 08:13 UTC, Krekep approved these changes
Зачтено

2024-11-11 16:19 UTC, merged